# permissions for end users to edit workshopsessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: advok8s-course-director
    app.kubernetes.io/managed-by: kustomize
  name: workshopsession-editor-role
rules:
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshopsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshopsessions/status
  verbs:
  - get
