# permissions for end users to view workshops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: advok8s-course-director
    app.kubernetes.io/managed-by: kustomize
  name: workshop-viewer-role
rules:
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshops/status
  verbs:
  - get
