# permissions for end users to view workshopinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: advok8s-course-director
    app.kubernetes.io/managed-by: kustomize
  name: workshopinstance-viewer-role
rules:
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshopinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - course-director.advok8s.io
  resources:
  - workshopinstances/status
  verbs:
  - get
